radar_record:
    - /compressed_image
    - /compressed_image2
    - /livox/lidar
    - /match_info
    - /sentry2RadarData
    - /Radar2Sentry
    # - /hero_state
    - /gimbalUsartData
    - /GimbalPub
    - /lidar_detect
    - /key_usart_sender
    - /radio_buff
    - /radio_fire
    - /radio_hp
    - /radio_state
    - /robot_position

# 设置 数据集文件夹 相对于本yaml文件所在文件夹的储存位置：path = "...src/databag_tool/" + bags_relative_path , 用于 record 和 merge
bags_relative_path: ../../ros2bags/

# bags_relative_path: ../../../../../../home/tdt/rosbag/ros2bags/

# 强制停止时间，单次开机自启或启动后的停止时间
forced_stop_time: 1500
